version: "3.7"

services:
  nginx-server:
    image: nginx:stable-alpine
    container_name: nginx-tpeweb2-c
    ports:
      - ${NGINX_PORT}:80
    volumes:
      # mapping php code and files that nginx will serve
      - ./app:/var/www/app
      # mapping nginx configurations
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      # - mysql-db

  php:
    build:
      context: ./
      dockerfile: ./customPhp.Dockerfile
    image: php:7.4-fpm-custom
    container_name: php-tpeweb2-c
    volumes:
      # mapping the folder where the code php will be accessed by the php interpreter
      - ./app/src:/var/www/app/src
      - ~/.bashrc:/root/.bashrc

  mysql-db:
    image: mysql:8.0.26
    container_name: mysql-tpeweb2-c
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      # this is the pasword for the "root" user
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      
      
    volumes:
      - mysql-tpeweb2-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin-tpeweb2-c
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql-db
    environment:
      PMA_HOST: mysql-db

volumes:
  mysql-tpeweb2-data: