version: "3.7"

services:
  servidor-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - php
      - db-mysql

  php:
    image: php:7.4-alpine

  composer:
    image: composer
    command: install

  db-mysql:
    image: mysql
    ports:
      - "3306:3306"
      - "3307:3306"
    volumes:
      - "./db-mysql-data:/var/lib/mysql"

  php-my-admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysqldb
